/**
 * The gym PC's one-file setup (Settings → WhatsApp → Gym PC): a Windows .bat that puts the
 * WhatsApp gateway kit (public/gym-pc) on the PC with this gym's setup key and starts it with
 * Docker Desktop. Running it again updates the kit and keeps the linked WhatsApp.
 */

export const GYM_PC_SETUP_FILE = "RebuildFitness-WhatsApp.bat";

export function gymPcSetupBat(appUrl: string, key: string) {
  // Both go into the file as they are: only plain URL and key characters may.
  if (!/^https?:\/\/[A-Za-z0-9.:-]+$/.test(appUrl)) throw new Error("Unexpected app address.");
  if (!/^rfpc_[A-Za-z0-9_-]{20,}$/.test(key)) throw new Error("Unexpected setup key.");
  const lines = [
    "@echo off",
    "setlocal",
    "title Rebuild Fitness - WhatsApp on this PC",
    "rem Sends the gym's bills and member app links on WhatsApp from this PC.",
    "rem Double-click to set up. Run it again any time: it updates and keeps the linked WhatsApp.",
    `set "APP=${appUrl}"`,
    `set "KEY=${key}"`,
    'set "DIR=%USERPROFILE%\\RebuildFitnessWhatsApp"',
    'set "DD=%ProgramFiles%\\Docker\\Docker"',
    "echo.",
    "echo  Rebuild Fitness - WhatsApp on this PC",
    "echo  -------------------------------------",
    "echo.",
    "",
    "rem Docker Desktop runs the WhatsApp gateway (installed once).",
    'set "DOCKER=docker"',
    "where docker >nul 2>nul",
    'if errorlevel 1 if exist "%DD%\\resources\\bin\\docker.exe" set "DOCKER=%DD%\\resources\\bin\\docker.exe"',
    '"%DOCKER%" --version >nul 2>nul',
    "if errorlevel 1 goto nodocker",
    '"%DOCKER%" info >nul 2>nul',
    "if not errorlevel 1 goto running",
    "echo  Starting Docker Desktop (up to 5 minutes the first time)...",
    'if exist "%DD%\\Docker Desktop.exe" start "" "%DD%\\Docker Desktop.exe"',
    "set /a TRIES=0",
    ":waitdocker",
    "timeout /t 5 /nobreak >nul",
    '"%DOCKER%" info >nul 2>nul',
    "if not errorlevel 1 goto running",
    "set /a TRIES+=1",
    "if %TRIES% lss 60 goto waitdocker",
    "echo.",
    "echo  Docker Desktop did not start. Open Docker Desktop from the Start menu, wait",
    'echo  until it says "Engine running", then double-click this file again.',
    "goto end",
    "",
    ":running",
    "echo  Docker Desktop is running.",
    'if not exist "%DIR%" mkdir "%DIR%"',
    "echo  Getting the setup files from the app...",
    'curl.exe -fsSL "%APP%/gym-pc/docker-compose.yml" -o "%DIR%\\docker-compose.yml"',
    "if errorlevel 1 goto nofiles",
    'curl.exe -fsSL "%APP%/gym-pc/link.mjs" -o "%DIR%\\link.mjs"',
    "if errorlevel 1 goto nofiles",
    '>"%DIR%\\.env" echo APP_URL=%APP%',
    '>>"%DIR%\\.env" echo LINK_KEY=%KEY%',
    'cd /d "%DIR%"',
    "echo  Starting WhatsApp on this PC. The first time it downloads about 1 GB (5-15 minutes).",
    '"%DOCKER%" compose up -d',
    "if errorlevel 1 goto nostart",
    "echo.",
    "echo  Done! In about 2 minutes the app shows: Gym PC online.",
    "echo  Only the first time: in the app, Settings ^> WhatsApp ^> Show QR, and scan it on the",
    "echo  gym's phone (WhatsApp ^> Linked devices ^> Link a device).",
    "echo.",
    "echo  From now on it starts by itself when this PC starts. Keep Docker Desktop's",
    'echo  "Start Docker Desktop when you sign in" ticked (it is, unless someone changed it).',
    "echo.",
    'choice /c YN /t 30 /d N /m "Keep this PC from sleeping while it is plugged in (so WhatsApp keeps sending)"',
    "if errorlevel 2 goto opened",
    "powercfg /change standby-timeout-ac 0",
    "echo  OK: this PC stays awake while plugged in.",
    ":opened",
    'start "" "%APP%/settings?tab=whatsapp"',
    "goto end",
    "",
    ":nodocker",
    "echo  Docker Desktop is not installed yet. It is free; install it once:",
    "echo    1. The download page opens now: Download for Windows, run it, keep the ticks.",
    "echo    2. Restart the PC if it asks, open Docker Desktop, accept, skip the sign-in.",
    "echo    3. Double-click this file again.",
    'start "" "https://www.docker.com/products/docker-desktop/"',
    "goto end",
    "",
    ":nofiles",
    "echo  Could not download the setup files. Check the internet and run this file again.",
    "goto end",
    "",
    ":nostart",
    "echo  Docker could not start WhatsApp. Check the internet, then run this file again.",
    "echo  If it keeps failing, send a photo of this window to support.",
    "goto end",
    "",
    ":end",
    "echo.",
    "pause",
  ];
  // Windows line endings: batch labels and goto need them.
  return `${lines.join("\r\n")}\r\n`;
}
