import { useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Field, FormDialog } from "@/components/common/form-dialog";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { useAuth } from "@/hooks/use-auth";
import { formatPrice, todayISO } from "@/lib/format";
import { calculateInvoiceTotals } from "@/lib/invoice-utils";
import { createInvoiceSchema, type CreateInvoiceInput } from "@/lib/invoice-validation";
import { createInvoice } from "@/services/invoices.service";
import { firestoreErrorMessage } from "@/services/firestore.service";
import type { BusinessBillingSettings, Client, GymPackage, InvoiceItem, PaymentMethod } from "@/types/models";
import { PAYMENT_METHODS } from "@/types/models";

const emptyItem=():InvoiceItem=>({name:"",description:"",quantity:1,unitPrice:0,total:0,packageId:null});
export function CreateBillDialog({open,onOpenChange,clients,packages,settings,initialClientId}:{open:boolean;onOpenChange:(v:boolean)=>void;clients:Client[];packages:GymPackage[];settings:BusinessBillingSettings;initialClientId?:string|undefined}){
 const {user}=useAuth(),today=todayISO();const [clientId,setClientId]=useState(initialClientId??"");const [items,setItems]=useState<InvoiceItem[]>([emptyItem()]);const [discount,setDiscount]=useState(0);const [amountPaid,setAmountPaid]=useState(0);const [method,setMethod]=useState<PaymentMethod>("Cash");const [invoiceDate,setInvoiceDate]=useState(today);const [dueDate,setDueDate]=useState(today);const [notes,setNotes]=useState("");const [createMembership,setCreateMembership]=useState(true);const [startDate,setStartDate]=useState(today);const [confirm,setConfirm]=useState(false);const [saving,setSaving]=useState(false);const [errors,setErrors]=useState<Record<string,string>>({});
 const totals=useMemo(()=>calculateInvoiceTotals(items,discount,settings,amountPaid),[items,discount,settings,amountPaid]);const selectedClient=clients.find(c=>c.id===clientId);
 const updateItem=(index:number,patch:Partial<InvoiceItem>)=>setItems(old=>old.map((item,i)=>i===index?{...item,...patch,total:(patch.quantity??item.quantity)*(patch.unitPrice??item.unitPrice)}:item));
 const choosePackage=(index:number,id:string)=>{const pkg=packages.find(p=>p.id===id);if(pkg)updateItem(index,{packageId:pkg.id,name:pkg.name,description:`${pkg.durationDays} day membership`,unitPrice:pkg.price});};
 const input=():CreateInvoiceInput=>({clientId,items:items.map(i=>({...i,total:i.quantity*i.unitPrice})),discount,amountPaid,paymentMethod:method,invoiceDate,dueDate,notes,createMembership,membershipStartDate:startDate,previousAction:"expired"});
 const prepare=()=>{const parsed=createInvoiceSchema.safeParse(input());if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return;}if(amountPaid>totals.total){setErrors({amountPaid:"Amount paid cannot exceed total"});return;}setErrors({});setConfirm(true)};
 const submit=async()=>{if(!selectedClient||!user||saving)return;setConfirm(false);setSaving(true);try{const invoice=await createInvoice(input(),{client:selectedClient,packages,settings,staff:{uid:user.uid,name:user.displayName||user.email||"Staff"}});toast.success("Invoice generated",{description:invoice.invoiceNumber});onOpenChange(false);}catch(e){toast.error("Couldn't generate invoice",{description:firestoreErrorMessage(e)});}finally{setSaving(false)}};
 return <><FormDialog open={open} onOpenChange={onOpenChange} title="Create Bill" description="Create a membership or service invoice and record payment." className="sm:max-w-4xl" footer={<><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={prepare}>{saving?"Generating…":"Review & generate invoice"}</Button></>}><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-6"><section><h3 className="text-card-title">1. Client</h3><Field label="Select client" htmlFor="bill-client" required error={errors["clientId"]}><Select value={clientId} onValueChange={setClientId}><SelectTrigger id="bill-client"><SelectValue placeholder="Search or select a client"/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.fullName} · {c.phone} · {c.clientCode}</SelectItem>)}</SelectContent></Select></Field>{selectedClient?<div className="mt-3 rounded-xl border border-border bg-muted/40 p-3"><p className="font-semibold">{selectedClient.fullName}</p><p className="text-meta">{selectedClient.phone} · {selectedClient.currentMembership?.packageName||"No current membership"}</p></div>:null}</section>
 <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-card-title">2. Items</h3><Button type="button" size="sm" variant="outline" onClick={()=>setItems(v=>[...v,emptyItem()])}><Plus/> Custom service</Button></div>{errors["items"]?<p className="text-xs text-destructive">{errors["items"]}</p>:null}{items.map((item,index)=><div key={index} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-2"><Field label="Package (optional)" htmlFor={`pkg-${index}`}><Select value={item.packageId??"custom"} onValueChange={v=>v==="custom"?updateItem(index,{packageId:null,name:"",description:"",unitPrice:0}):choosePackage(index,v)}><SelectTrigger id={`pkg-${index}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="custom">Custom service</SelectItem>{packages.filter(p=>p.isActive).map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {formatPrice(p.price)}</SelectItem>)}</SelectContent></Select></Field><Field label="Item name" htmlFor={`item-${index}`}><Input id={`item-${index}`} value={item.name} onChange={e=>updateItem(index,{name:e.target.value})}/></Field><Field label="Description" htmlFor={`desc-${index}`}><Input id={`desc-${index}`} value={item.description} onChange={e=>updateItem(index,{description:e.target.value})}/></Field><div className="grid grid-cols-[1fr_1.4fr_auto] gap-2"><Field label="Qty" htmlFor={`qty-${index}`}><Input id={`qty-${index}`} type="number" min="1" value={item.quantity} onChange={e=>updateItem(index,{quantity:Number(e.target.value)})}/></Field><Field label="Unit price" htmlFor={`price-${index}`}><Input id={`price-${index}`} type="number" min="0" value={item.unitPrice} onChange={e=>updateItem(index,{unitPrice:Number(e.target.value)})}/></Field><Button className="mt-6" variant="ghost" size="icon" aria-label="Remove item" disabled={items.length===1} onClick={()=>setItems(v=>v.filter((_,i)=>i!==index))}><Trash2/></Button></div></div>)}</section>
 <section className="grid gap-3 sm:grid-cols-2"><h3 className="text-card-title sm:col-span-2">3. Payment & invoice details</h3><Field label="Discount" htmlFor="discount" error={errors["discount"]}><Input id="discount" type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></Field><Field label="Amount paid" htmlFor="amount-paid" error={errors["amountPaid"]}><Input id="amount-paid" type="number" min="0" max={totals.total} value={amountPaid} onChange={e=>setAmountPaid(Number(e.target.value))}/></Field><Field label="Payment method" htmlFor="payment-method"><Select value={method} onValueChange={v=>setMethod(v as PaymentMethod)}><SelectTrigger id="payment-method"><SelectValue/></SelectTrigger><SelectContent>{PAYMENT_METHODS.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label="Invoice date" htmlFor="invoice-date"><Input id="invoice-date" type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)}/></Field><Field label="Due date" htmlFor="due-date" error={errors["dueDate"]}><Input id="due-date" type="date" min={invoiceDate} value={dueDate} onChange={e=>setDueDate(e.target.value)}/></Field><Field label="Notes" htmlFor="invoice-notes" className="sm:col-span-2"><Textarea id="invoice-notes" value={notes} onChange={e=>setNotes(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm font-medium sm:col-span-2"><Checkbox checked={createMembership} onCheckedChange={v=>setCreateMembership(v===true)}/> Create membership from selected package</label>{createMembership?<Field label="Membership start date" htmlFor="membership-start"><Input id="membership-start" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field>:null}</section></div>
 <aside className="h-fit rounded-2xl bg-foreground p-5 text-background lg:sticky lg:top-0"><p className="text-xs font-bold uppercase tracking-wider text-background/60">Bill summary</p><dl className="mt-5 space-y-3 text-sm">{[["Subtotal",totals.subtotal],["Discount",-totals.discount],...(totals.tax?[[`Tax (${settings.taxRate}%)`,totals.tax] as [string,number]]:[]),["Total",totals.total],["Paid",totals.amountPaid],["Balance",totals.balanceDue]].map(([k,v])=><div key={k} className="flex justify-between gap-3"><dt>{k}</dt><dd className="font-bold tabular-nums">{formatPrice(v as number)}</dd></div>)}</dl><div className="mt-5 border-t border-background/20 pt-4"><p className="text-xs text-background/60">Status</p><p className="mt-1 text-lg font-bold">{totals.balanceDue===0?"Paid":totals.amountPaid?"Partial":"Pending"}</p></div></aside></div></FormDialog><ConfirmDialog open={confirm} onOpenChange={setConfirm} title="Generate this invoice?" description={`This creates a permanent ${formatPrice(totals.total)} financial record${createMembership?" and membership":""}. It cannot be deleted.`} confirmLabel="Generate invoice" onConfirm={()=>void submit()}/></>;
}