import { Copy, Download, ExternalLink, MessageCircle, Printer } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { getInvoicePublicUrl } from "@/lib/invoice-utils";
import type { Invoice } from "@/types/models";
import { sendWhatsAppMessage } from "@/services/whatsapp.service";
import { DEFAULT_WHATSAPP_SETTINGS,subscribeWhatsAppSettings } from "@/services/whatsapp-settings.service";
import { useLive } from "@/hooks/use-live-query";

export function InvoiceActions({invoice,compact=false}:{invoice:Invoice;compact?:boolean}){const settings=useLive(subscribeWhatsAppSettings,DEFAULT_WHATSAPP_SETTINGS,[]);const copy=async()=>{await navigator.clipboard.writeText(getInvoicePublicUrl(invoice));toast.success("Invoice link copied")};const open=()=>window.open(getInvoicePublicUrl(invoice),"_blank","noopener,noreferrer");const send=async()=>{try{const result=await sendWhatsAppMessage({client:{id:invoice.clientId,fullName:invoice.clientNameSnapshot,phone:invoice.clientPhoneSnapshot,whatsappPhone:invoice.clientPhoneSnapshot,whatsappOptIn:true},type:"invoice",referenceId:invoice.id,templateName:settings.data.invoiceTemplate,templateLanguage:settings.data.templateLanguage,parameters:[invoice.clientNameSnapshot,invoice.invoiceNumber,getInvoicePublicUrl(invoice)],messagePreview:`Invoice ${invoice.invoiceNumber}: ${getInvoicePublicUrl(invoice)}`,provider:settings.data.mode});toast.success(result.duplicate?"Invoice message already queued":settings.data.mode==="mock"?"Invoice queued in Mock mode":"Invoice sent to WhatsApp")}catch(error){toast.error(error instanceof Error?error.message:"Couldn't send invoice")}};return <div className="flex flex-wrap gap-2"><Button size={compact?"icon-sm":"sm"} variant="outline" aria-label="View public invoice" onClick={open}><ExternalLink/>{compact?null:"View"}</Button><Button size={compact?"icon-sm":"sm"} variant="outline" aria-label="Download PDF" disabled={!invoice.pdfUrl} asChild={Boolean(invoice.pdfUrl)}>{invoice.pdfUrl?<a href={invoice.pdfUrl} target="_blank" rel="noreferrer"><Download/>{compact?null:"PDF"}</a>:<><Download/>{compact?null:"PDF"}</>}</Button><Button size={compact?"icon-sm":"sm"} variant="outline" aria-label="Copy public link" onClick={()=>void copy()}><Copy/>{compact?null:"Copy link"}</Button><Button size={compact?"icon-sm":"sm"} variant="outline" aria-label="Send invoice via WhatsApp" onClick={()=>void send()}><MessageCircle/>{compact?null:"WhatsApp"}</Button><Button size={compact?"icon-sm":"sm"} variant="outline" aria-label="Print invoice" onClick={open}><Printer/>{compact?null:"Print"}</Button></div>}