import { doc, query, runTransaction, serverTimestamp, where, type DocumentData } from "@/lib/firestore";
import { db } from "@/lib/firebase";
import { enrollmentStatusSchema } from "@/lib/scheduling-validation";
import type { ClassEnrollment, Client, EnrollmentStatus, GroupClass } from "@/types/models";
import { col, COLLECTIONS, subscribeCollection, subscribeQuery, toDate } from "./firestore.service";
const mapEnrollment=(id:string,d:DocumentData):ClassEnrollment=>({id,groupClassId:d["groupClassId"]??"",clientId:d["clientId"]??"",clientNameSnapshot:d["clientNameSnapshot"]??"",enrolledAt:toDate(d["enrolledAt"]),status:d["status"]??"cancelled"});
export const subscribeClassEnrollments=(ok:(v:ClassEnrollment[])=>void,fail:(e:Error)=>void)=>subscribeCollection(COLLECTIONS.classEnrollments,mapEnrollment,ok,fail);
export const subscribeEnrollmentsForClass=(id:string,ok:(v:ClassEnrollment[])=>void,fail:(e:Error)=>void)=>subscribeQuery(query(col(COLLECTIONS.classEnrollments),where("groupClassId","==",id)),mapEnrollment,ok,fail);
export const subscribeClientEnrollments=(id:string,ok:(v:ClassEnrollment[])=>void,fail:(e:Error)=>void)=>subscribeQuery(query(col(COLLECTIONS.classEnrollments),where("clientId","==",id)),mapEnrollment,ok,fail);
export async function enrollClient(group:GroupClass,client:Client){const enrollmentRef=doc(db,COLLECTIONS.classEnrollments,`${group.id}_${client.id}`);const classRef=doc(db,COLLECTIONS.groupClasses,group.id);await runTransaction(db,async tx=>{const [classSnap,enrollmentSnap]=await Promise.all([tx.get(classRef),tx.get(enrollmentRef)]);if(!classSnap.exists())throw new Error("This class no longer exists.");const data=classSnap.data();if(data["status"]!=="scheduled")throw new Error("Only scheduled classes accept enrollments.");const booked=Number(data["bookedCount"]??0);if(enrollmentSnap.exists()&&enrollmentSnap.data()["status"]==="enrolled")throw new Error("This client is already enrolled.");if(booked>=Number(data["capacity"]??0))throw new Error("Class Full");tx.set(enrollmentRef,{groupClassId:group.id,clientId:client.id,clientNameSnapshot:client.fullName,enrolledAt:serverTimestamp(),status:"enrolled"});tx.update(classRef,{bookedCount:booked+1,updatedAt:serverTimestamp()});});}
export async function updateEnrollmentStatus(item:ClassEnrollment,status:EnrollmentStatus){const safe=enrollmentStatusSchema.parse(status);const enrollmentRef=doc(db,COLLECTIONS.classEnrollments,item.id);const classRef=doc(db,COLLECTIONS.groupClasses,item.groupClassId);await runTransaction(db,async tx=>{const [classSnap,enrollmentSnap]=await Promise.all([tx.get(classRef),tx.get(enrollmentRef)]);if(!enrollmentSnap.exists())throw new Error("Enrollment not found.");const old=enrollmentSnap.data()["status"] as EnrollmentStatus;const oldOccupies=old!=="cancelled";const newOccupies=safe!=="cancelled";if(classSnap.exists()&&oldOccupies!==newOccupies){const booked=Number(classSnap.data()["bookedCount"]??0);const capacity=Number(classSnap.data()["capacity"]??0);if(newOccupies&&booked>=capacity)throw new Error("Class Full");tx.update(classRef,{bookedCount:Math.max(0,booked+(newOccupies?1:-1)),updatedAt:serverTimestamp()});}tx.update(enrollmentRef,{status:safe});});}
