import { doc, getDocs, orderBy, query, serverTimestamp, updateDoc, where, writeBatch, type DocumentData } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { todayISO } from "@/lib/format";
import { assignmentStatusSchema, dietAssignmentSchema } from "@/lib/plan-validation";
import type { AssignmentStatus, DietAssignment, DietPlan } from "@/types/models";
import { col, COLLECTIONS, subscribeCollection, subscribeQuery, toDate } from "./firestore.service";
const mapAssignment=(id:string,d:DocumentData):DietAssignment=>({id,clientId:d["clientId"]??"",dietPlanId:d["dietPlanId"]??"",planNameSnapshot:d["planNameSnapshot"]??"",goalSnapshot:d["goalSnapshot"]??"Custom",dailyCaloriesSnapshot:Number(d["dailyCaloriesSnapshot"]??0),assignedDate:d["assignedDate"]??"",startDate:d["startDate"]??"",endDate:d["endDate"]??"",status:d["status"]??"cancelled",notes:d["notes"]??"",createdAt:toDate(d["createdAt"]),updatedAt:toDate(d["updatedAt"])});
const sort=(v:DietAssignment[])=>[...v].sort((a,b)=>b.startDate.localeCompare(a.startDate)||b.createdAt.getTime()-a.createdAt.getTime());
export const subscribeDietAssignments=(onData:(v:DietAssignment[])=>void,onError:(e:Error)=>void)=>subscribeCollection(COLLECTIONS.dietAssignments,mapAssignment,onData,onError,orderBy("createdAt","desc"));
export const subscribeClientDietAssignments=(clientId:string,onData:(v:DietAssignment[])=>void,onError:(e:Error)=>void)=>subscribeQuery(query(col(COLLECTIONS.dietAssignments),where("clientId","==",clientId)),mapAssignment,v=>onData(sort(v)),onError);
export async function createDietAssignment(input:{clientId:string;plan:DietPlan;startDate:string;endDate:string;notes:string}){const safe=dietAssignmentSchema.parse({clientId:input.clientId,dietPlanId:input.plan.id,startDate:input.startDate,endDate:input.endDate,notes:input.notes});const current=await getDocs(query(col(COLLECTIONS.dietAssignments),where("clientId","==",safe.clientId)));const batch=writeBatch(db);current.docs.filter(d=>d.data()["status"]==="active").forEach(d=>batch.update(d.ref,{status:"completed",updatedAt:serverTimestamp()}));const ref=doc(col(COLLECTIONS.dietAssignments));batch.set(ref,{clientId:safe.clientId,dietPlanId:input.plan.id,planNameSnapshot:input.plan.name,goalSnapshot:input.plan.goal,dailyCaloriesSnapshot:input.plan.dailyCalories,assignedDate:todayISO(),startDate:safe.startDate,endDate:safe.endDate,status:"active",notes:safe.notes,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();return ref.id;}
export async function updateDietAssignmentStatus(id:string,status:AssignmentStatus){await updateDoc(doc(db,COLLECTIONS.dietAssignments,id),{status:assignmentStatusSchema.parse(status),updatedAt:serverTimestamp()});}
