import { doc,getDoc,orderBy,query,runTransaction,serverTimestamp,updateDoc,where,writeBatch,type DocumentData } from "firebase/firestore";import { db } from "@/lib/firebase";import { todayISO } from "@/lib/format";import type { FollowUp,FollowUpPriority,FollowUpSource } from "@/types/models";import { col,COLLECTIONS,subscribeCollection,subscribeQuery,toDate } from "./firestore.service";
export type FollowUpInput={clientId:string;inquiryId:string|null;clientNameSnapshot:string;phoneSnapshot:string;source:FollowUpSource;reason:string;notes:string;followUpDate:string;followUpTime:string;priority:FollowUpPriority;assignedTo:string;nextAction:string;outcome:string;automated?:boolean;parentFollowUpId?:string|null};
export const mapFollowUp=(id:string,d:DocumentData):FollowUp=>({id,clientId:d["clientId"]??"",inquiryId:d["inquiryId"]??null,clientNameSnapshot:d["clientNameSnapshot"]??"",phoneSnapshot:d["phoneSnapshot"]??"",source:d["source"]??"general",reason:d["reason"]??"",notes:d["notes"]??"",followUpDate:d["followUpDate"]??"",followUpTime:d["followUpTime"]??"09:00",status:d["status"]??"pending",priority:d["priority"]??"medium",assignedTo:d["assignedTo"]??"",lastContactDate:d["lastContactDate"]??null,nextAction:d["nextAction"]??"",outcome:d["outcome"]??"",automated:Boolean(d["automated"]),parentFollowUpId:d["parentFollowUpId"]??null,createdAt:toDate(d["createdAt"]),updatedAt:toDate(d["updatedAt"])});
export const subscribeFollowUps=(ok:(x:FollowUp[])=>void,fail:(e:Error)=>void)=>subscribeCollection(COLLECTIONS.followups,mapFollowUp,items=>ok(items.sort((a,b)=>`${a.followUpDate}${a.followUpTime}`.localeCompare(`${b.followUpDate}${b.followUpTime}`))),fail,orderBy("createdAt","desc"));
export const subscribeClientFollowUps=(clientId:string,ok:(x:FollowUp[])=>void,fail:(e:Error)=>void)=>subscribeQuery(query(col(COLLECTIONS.followups),where("clientId","==",clientId)),mapFollowUp,x=>ok(x.sort((a,b)=>b.followUpDate.localeCompare(a.followUpDate))),fail);
export async function saveFollowUp(input:FollowUpInput,id?:string){const ref=id?doc(db,COLLECTIONS.followups,id):doc(col(COLLECTIONS.followups));await runTransaction(db,async tx=>{const now=serverTimestamp();tx.set(ref,{...input,automated:Boolean(input.automated),parentFollowUpId:input.parentFollowUpId??null,status:"pending",lastContactDate:null,...(id?{}:{createdAt:now}),updatedAt:now},{merge:Boolean(id)});const activity=doc(col(COLLECTIONS.automationActivities));tx.set(activity,{type:"followup_created",referenceId:ref.id,clientId:input.clientId,clientNameSnapshot:input.clientNameSnapshot,description:`Follow-up created: ${input.reason}`,createdAt:now,updatedAt:now})});return ref.id}
export async function completeFollowUp(item:FollowUp,input:{outcome:string;notes:string;nextAction:string;nextFollowUpDate?:string;nextFollowUpTime?:string}){const batch=writeBatch(db),now=serverTimestamp(),ref=doc(db,COLLECTIONS.followups,item.id);batch.update(ref,{status:"completed",outcome:input.outcome,notes:input.notes,lastContactDate:todayISO(),nextAction:input.nextAction,updatedAt:now});const activity=doc(col(COLLECTIONS.automationActivities));batch.set(activity,{type:"followup_completed",referenceId:item.id,clientId:item.clientId,clientNameSnapshot:item.clientNameSnapshot,description:`Follow-up completed${input.outcome?`: ${input.outcome}`:""}`,createdAt:now,updatedAt:now});if(input.nextFollowUpDate){const next=doc(col(COLLECTIONS.followups));batch.set(next,{clientId:item.clientId,inquiryId:item.inquiryId,clientNameSnapshot:item.clientNameSnapshot,phoneSnapshot:item.phoneSnapshot,source:item.source,reason:item.reason,notes:"",followUpDate:input.nextFollowUpDate,followUpTime:input.nextFollowUpTime||"09:00",status:"pending",priority:item.priority,assignedTo:item.assignedTo,lastContactDate:todayISO(),nextAction:input.nextAction,outcome:"",automated:false,parentFollowUpId:item.id,createdAt:now,updatedAt:now})}await batch.commit()}
export async function rescheduleFollowUp(id:string,date:string,time:string){await updateDoc(doc(db,COLLECTIONS.followups,id),{followUpDate:date,followUpTime:time,status:"pending",updatedAt:serverTimestamp()})}
export async function cancelFollowUp(id:string){await updateDoc(doc(db,COLLECTIONS.followups,id),{status:"cancelled",updatedAt:serverTimestamp()})}
export async function syncInquiryFollowUp(inquiryId:string){const inquiryRef=doc(db,COLLECTIONS.inquiries,inquiryId),stableRef=doc(db,COLLECTIONS.followups,`inquiry_${inquiryId}`);await runTransaction(db,async tx=>{const [inq,existing]=await Promise.all([tx.get(inquiryRef),tx.get(stableRef)]);if(!inq.exists())return;const d=inq.data(),date=d["nextFollowUpDate"] as string|null;if(!date)return;const now=serverTimestamp();tx.set(stableRef,{clientId:d["clientId"]??"",inquiryId,clientNameSnapshot:d["name"]??"",phoneSnapshot:d["phone"]??"",source:"inquiry",reason:"Inquiry follow-up",notes:existing.data()?.["notes"]??d["notes"]??"",followUpDate:date,followUpTime:existing.data()?.["followUpTime"]??"09:00",status:existing.data()?.["status"]==="completed"?"completed":"pending",priority:existing.data()?.["priority"]??"medium",assignedTo:existing.data()?.["assignedTo"]??"",lastContactDate:existing.data()?.["lastContactDate"]??null,nextAction:existing.data()?.["nextAction"]??"Contact inquiry",outcome:existing.data()?.["outcome"]??"",automated:false,parentFollowUpId:null,createdAt:existing.data()?.["createdAt"]??now,updatedAt:now},{merge:true});tx.update(inquiryRef,{followupId:stableRef.id,updatedAt:now})})}
