import { doc, getDoc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc, where, type DocumentData } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { db, storage } from "@/lib/firebase";
import { createInvoiceSchema, type CreateInvoiceInput } from "@/lib/invoice-validation";
import { calculateInvoiceTotals, createPublicToken, derivePaymentStatus } from "@/lib/invoice-utils";
import { generateInvoicePdf } from "@/lib/invoice-pdf";
import { calculateEndDate } from "./memberships.service";
import { col, COLLECTIONS, subscribeCollection, subscribeQuery, toDate } from "./firestore.service";
import type { BusinessBillingSettings, Client, GymPackage, Invoice, PublicInvoice } from "@/types/models";

export const mapInvoice=(id:string,d:DocumentData):Invoice=>({id,invoiceNumber:d["invoiceNumber"]??"",clientId:d["clientId"]??"",clientNameSnapshot:d["clientNameSnapshot"]??"",clientPhoneSnapshot:d["clientPhoneSnapshot"]??"",clientEmailSnapshot:d["clientEmailSnapshot"]??"",membershipId:d["membershipId"]??null,packageId:d["packageId"]??null,items:Array.isArray(d["items"])?d["items"]:[],subtotal:Number(d["subtotal"]??0),discount:Number(d["discount"]??0),tax:Number(d["tax"]??0),total:Number(d["total"]??0),amountPaid:Number(d["amountPaid"]??0),balanceDue:Number(d["balanceDue"]??0),paymentStatus:d["paymentStatus"]??"pending",paymentMethod:d["paymentMethod"]??"Other",invoiceDate:d["invoiceDate"]??"",dueDate:d["dueDate"]??"",notes:d["notes"]??"",pdfUrl:d["pdfUrl"]??"",publicToken:d["publicToken"]??"",createdBy:d["createdBy"]??"Staff",createdByUid:d["createdByUid"]??"",createdAt:toDate(d["createdAt"]),updatedAt:toDate(d["updatedAt"])});
export const mapPublicInvoice=(token:string,d:DocumentData):PublicInvoice=>({publicToken:token,invoiceNumber:d["invoiceNumber"]??"",clientName:d["clientName"]??"",clientPhone:d["clientPhone"]??"",clientEmail:d["clientEmail"]??"",items:Array.isArray(d["items"])?d["items"]:[],subtotal:Number(d["subtotal"]??0),discount:Number(d["discount"]??0),tax:Number(d["tax"]??0),total:Number(d["total"]??0),amountPaid:Number(d["amountPaid"]??0),balanceDue:Number(d["balanceDue"]??0),paymentStatus:d["paymentStatus"]??"pending",paymentMethod:d["paymentMethod"]??"Other",invoiceDate:d["invoiceDate"]??"",dueDate:d["dueDate"]??"",pdfUrl:d["pdfUrl"]??"",business:d["business"],updatedAt:toDate(d["updatedAt"])});
export function subscribeInvoices(ok:(v:Invoice[])=>void,fail:(e:Error)=>void){return subscribeCollection(COLLECTIONS.invoices,mapInvoice,ok,fail,orderBy("createdAt","desc"));}
export function subscribeClientInvoices(clientId:string,ok:(v:Invoice[])=>void,fail:(e:Error)=>void){return subscribeQuery(query(col(COLLECTIONS.invoices),where("clientId","==",clientId)),mapInvoice,v=>ok(v.sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime())),fail);}
export function subscribePublicInvoice(token:string,ok:(v:PublicInvoice|null)=>void,fail:(e:Error)=>void){return onSnapshot(doc(db,COLLECTIONS.publicInvoices,token),s=>ok(s.exists()?mapPublicInvoice(token,s.data()):null),fail);}

export async function createInvoice(input:CreateInvoiceInput,context:{client:Client;packages:GymPackage[];settings:BusinessBillingSettings;staff:{uid:string;name:string}}){
 const data=createInvoiceSchema.parse(input),totals=calculateInvoiceTotals(data.items,data.discount,context.settings,data.amountPaid);if(data.amountPaid>totals.total)throw new Error("Amount paid cannot exceed invoice total.");
 const invoiceRef=doc(col(COLLECTIONS.invoices)),token=createPublicToken(),publicRef=doc(db,COLLECTIONS.publicInvoices,token),counterRef=doc(db,COLLECTIONS.settings,"counters");let invoiceNumber="",membershipId:string|null=null;
 await runTransaction(db,async tx=>{const counter=await tx.get(counterRef);const year=new Date(`${data.invoiceDate}T00:00:00`).getFullYear();const key=`invoiceSeq${year}`;const next=Number(counter.data()?.[key]??0)+1;invoiceNumber=`${context.settings.invoicePrefix}-${year}-${String(next).padStart(6,"0")}`;const packageItem=data.items.find(i=>i.packageId);const pkg=packageItem?context.packages.find(p=>p.id===packageItem.packageId):null;if(data.createMembership&&pkg){const membershipRef=doc(col(COLLECTIONS.memberships));membershipId=membershipRef.id;const endDate=calculateEndDate(data.membershipStartDate,pkg.durationDays),status=data.membershipStartDate>data.invoiceDate?"pending":"active";tx.set(membershipRef,{clientId:context.client.id,packageId:pkg.id,packageNameSnapshot:pkg.name,priceSnapshot:pkg.price,durationDaysSnapshot:pkg.durationDays,startDate:data.membershipStartDate,endDate,status,invoiceId:invoiceRef.id,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(status==="active")tx.update(doc(db,COLLECTIONS.clients,context.client.id),{currentMembership:{membershipId:membershipRef.id,packageName:pkg.name,startDate:data.membershipStartDate,endDate,status},status:"active",updatedAt:serverTimestamp()});}
 const items=data.items.map(i=>({...i,total:i.quantity*i.unitPrice}));const payload={invoiceNumber,clientId:context.client.id,clientNameSnapshot:context.client.fullName,clientPhoneSnapshot:context.client.phone,clientEmailSnapshot:context.client.email,membershipId,packageId:data.items.find(i=>i.packageId)?.packageId??null,items,...totals,paymentStatus:derivePaymentStatus(totals.total,totals.amountPaid),paymentMethod:data.paymentMethod,invoiceDate:data.invoiceDate,dueDate:data.dueDate,notes:data.notes,pdfUrl:"",publicToken:token,createdBy:context.staff.name,createdByUid:context.staff.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};tx.set(counterRef,{[key]:next,updatedAt:serverTimestamp()},{merge:true});tx.set(invoiceRef,payload);tx.set(publicRef,{publicToken:token,invoiceNumber,clientName:context.client.fullName,clientPhone:context.client.phone,clientEmail:context.client.email,items,...totals,paymentStatus:payload.paymentStatus,paymentMethod:data.paymentMethod,invoiceDate:data.invoiceDate,dueDate:data.dueDate,pdfUrl:"",business:context.settings,updatedAt:serverTimestamp()});});
 const snap=await getDoc(invoiceRef);const invoice=mapInvoice(invoiceRef.id,snap.data()??{});await generateAndUploadInvoicePdf(invoice,context.settings);return {...invoice,pdfUrl:(await getDoc(invoiceRef)).data()?.["pdfUrl"]??""};
}
export async function generateAndUploadInvoicePdf(invoice:Invoice,settings:BusinessBillingSettings){const bytes=await generateInvoicePdf(invoice,settings);const body=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const storageRef=ref(storage,`invoices/${invoice.id}/${invoice.publicToken}.pdf`);await uploadBytes(storageRef,new Blob([body],{type:"application/pdf"}),{contentType:"application/pdf"});const pdfUrl=await getDownloadURL(storageRef);await Promise.all([updateDoc(doc(db,COLLECTIONS.invoices,invoice.id),{pdfUrl,updatedAt:serverTimestamp()}),updateDoc(doc(db,COLLECTIONS.publicInvoices,invoice.publicToken),{pdfUrl,updatedAt:serverTimestamp()})]);return pdfUrl;}