import { useEffect, useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { CalendarRange, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { FormDialog, Field } from "@/components/common/form-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLive } from "@/hooks/use-live-query";
import { addDaysISO, formatDateISO, todayISO } from "@/lib/format";
import { createWorkoutAssignment } from "@/services/workout-assignments.service";
import { subscribeWorkoutPlans } from "@/services/workout-plans.service";
import { firestoreErrorMessage } from "@/services/firestore.service";
import type { WorkoutPlan } from "@/types/models";
export function AddWorkoutDialog({open,onOpenChange,clientId}:{open:boolean;onOpenChange:(v:boolean)=>void;clientId:string}){const plans=useLive<WorkoutPlan[]>(open?subscribeWorkoutPlans:null,[],[open]);const active=plans.data.filter(p=>p.isActive);const [planId,setPlanId]=useState("");const [startDate,setStartDate]=useState(todayISO());const [notes,setNotes]=useState("");const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false);useEffect(()=>{if(open){setPlanId("");setStartDate(todayISO());setNotes("");setError(null)}},[open]);const plan=active.find(p=>p.id===planId)??null;const endDate=useMemo(()=>plan?addDaysISO(startDate,plan.durationWeeks*7):"",[plan,startDate]);const submit=async()=>{if(!plan)return setError("Select a workout plan");setSaving(true);try{await createWorkoutAssignment({clientId,plan,startDate,notes});toast.success("Workout plan assigned",{description:plan.name});onOpenChange(false)}catch(e){setError(firestoreErrorMessage(e))}finally{setSaving(false)}};return <FormDialog open={open} onOpenChange={onOpenChange} title="Assign workout plan" description="A new active plan completes the previous active assignment while preserving its history." footer={<><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>void submit()} disabled={saving||!plan}>{saving?<Loader2 className="animate-spin"/>:null}Assign plan</Button></>}><div className="grid gap-4">{!plans.loading&&!active.length?<div className="rounded-xl border border-warning/40 bg-warning/10 p-4 text-sm">No active workout plans. <Link to="/workout-plans" className="font-semibold underline">Create one first</Link>.</div>:null}<Field label="Workout plan" htmlFor="wa-plan" error={error??undefined} required><Select value={planId} onValueChange={setPlanId}><SelectTrigger id="wa-plan" className="w-full"><SelectValue placeholder="Select a plan"/></SelectTrigger><SelectContent>{active.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {p.durationWeeks} weeks</SelectItem>)}</SelectContent></Select></Field><Field label="Start date" htmlFor="wa-start" required><Input id="wa-start" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field><Field label="Notes" htmlFor="wa-notes"><Textarea id="wa-notes" maxLength={1000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>{plan?<div className="rounded-xl border border-border bg-muted/40 p-4"><p className="flex items-center gap-2 font-semibold"><CalendarRange className="size-4"/> Assignment summary</p><p className="text-meta mt-2">{plan.goal} · {plan.daysPerWeek} days/week</p><p className="mt-1 text-sm font-medium">{formatDateISO(startDate)} → {formatDateISO(endDate)}</p></div>:null}</div></FormDialog>}
