import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { FormDialog, Field } from "@/components/common/form-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLive } from "@/hooks/use-live-query";
import { addDaysISO, todayISO } from "@/lib/format";
import { createDietAssignment } from "@/services/diet-assignments.service";
import { subscribeDietPlans } from "@/services/diet-plans.service";
import { firestoreErrorMessage } from "@/services/firestore.service";
import type { DietPlan } from "@/types/models";
export function AddDietDialog({open,onOpenChange,clientId}:{open:boolean;onOpenChange:(v:boolean)=>void;clientId:string}){const plans=useLive<DietPlan[]>(open?subscribeDietPlans:null,[],[open]);const active=plans.data.filter(p=>p.isActive);const [planId,setPlanId]=useState("");const [startDate,setStartDate]=useState(todayISO());const [endDate,setEndDate]=useState(addDaysISO(todayISO(),30));const [notes,setNotes]=useState("");const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false);useEffect(()=>{if(open){setPlanId("");setStartDate(todayISO());setEndDate(addDaysISO(todayISO(),30));setNotes("");setError(null)}},[open]);const plan=active.find(p=>p.id===planId)??null;const submit=async()=>{if(!plan)return setError("Select a diet plan");setSaving(true);try{await createDietAssignment({clientId,plan,startDate,endDate,notes});toast.success("Diet plan assigned",{description:plan.name});onOpenChange(false)}catch(e){setError(firestoreErrorMessage(e))}finally{setSaving(false)}};return <FormDialog open={open} onOpenChange={onOpenChange} title="Assign diet plan" description="A new active plan completes the previous active assignment while preserving its history." footer={<><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>void submit()} disabled={saving||!plan}>{saving?<Loader2 className="animate-spin"/>:null}Assign plan</Button></>}><div className="grid gap-4">{!plans.loading&&!active.length?<div className="rounded-xl border border-warning/40 bg-warning/10 p-4 text-sm">No active diet plans. <Link to="/diet-plans" className="font-semibold underline">Create one first</Link>.</div>:null}<Field label="Diet plan" htmlFor="da-plan" error={error??undefined} required><Select value={planId} onValueChange={setPlanId}><SelectTrigger id="da-plan" className="w-full"><SelectValue placeholder="Select a plan"/></SelectTrigger><SelectContent>{active.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {p.dailyCalories} kcal</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start date" htmlFor="da-start" required><Input id="da-start" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></Field><Field label="End date" htmlFor="da-end" required><Input id="da-end" type="date" min={startDate} value={endDate} onChange={e=>setEndDate(e.target.value)}/></Field></div><Field label="Notes" htmlFor="da-notes"><Textarea id="da-notes" maxLength={1000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div></FormDialog>}
