import { Dumbbell, Plus, Salad, XCircle } from "lucide-react";
import { EmptyState } from "@/components/common/empty-state";
import { ErrorState } from "@/components/common/error-state";
import { Shimmer } from "@/components/common/loading-state";
import { StatusPill } from "@/components/common/status-pill";
import { Button } from "@/components/ui/button";
import { ASSIGNMENT_STATUS_META, formatDateISO } from "@/lib/format";
import type { DietAssignment, WorkoutAssignment } from "@/types/models";

type Props =
 | { kind:"workout"; items:WorkoutAssignment[]; loading:boolean; error:Error|null; onAdd:()=>void; onClose:(item:WorkoutAssignment)=>void }
 | { kind:"diet"; items:DietAssignment[]; loading:boolean; error:Error|null; onAdd:()=>void; onClose:(item:DietAssignment)=>void };
export function AssignmentSection(props:Props){const isWorkout=props.kind==="workout";const Icon=isWorkout?Dumbbell:Salad;const current=props.items.find(i=>i.status==="active")??null;if(props.loading)return <Shimmer className="h-40 w-full rounded-2xl"/>;if(props.error)return <ErrorState error={props.error} title={`Couldn't load ${props.kind} assignments`}/>;if(!props.items.length)return <EmptyState icon={Icon} title={`No ${props.kind} plan assigned`} description={`Assign a ${props.kind} plan to start this member's ${isWorkout?"training":"nutrition"} history.`} action={<Button onClick={props.onAdd}><Plus/> Assign {props.kind} plan</Button>}/>;return <div className="space-y-4">{current?<section className="surface-card relative overflow-hidden p-5"><span className="absolute inset-x-0 top-0 h-0.5 bg-success"/><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-eyebrow">Current {props.kind} plan</p><h2 className="text-section-title mt-1 truncate">{current.planNameSnapshot}</h2><p className="text-meta">{current.goalSnapshot} · {formatDateISO(current.startDate)} → {formatDateISO(current.endDate)}</p>{isWorkout?null:<p className="mt-2 font-semibold tabular-nums">{(current as DietAssignment).dailyCaloriesSnapshot} kcal / day</p>}{current.notes?<p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{current.notes}</p>:null}</div><div className="flex shrink-0 flex-wrap gap-2"><Button onClick={props.onAdd}><Plus/> New plan</Button><Button variant="ghost" onClick={()=>props.onClose(current as never)}><XCircle/> Cancel</Button></div></div></section>:<div className="flex justify-end"><Button onClick={props.onAdd}><Plus/> Assign {props.kind} plan</Button></div>}<section className="surface-card overflow-hidden"><h2 className="text-section-title border-b border-border p-5">{isWorkout?"Workout":"Diet"} history</h2><ul className="divide-y divide-border">{props.items.map(item=><li key={item.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:gap-4 sm:px-5"><div className="min-w-0 flex-1"><p className="truncate font-semibold">{item.planNameSnapshot}</p><p className="text-meta">{item.goalSnapshot} · {formatDateISO(item.startDate)} → {formatDateISO(item.endDate)}</p></div><div className="flex items-center justify-between gap-3 sm:justify-end">{isWorkout?null:<span className="text-sm font-semibold tabular-nums">{(item as DietAssignment).dailyCaloriesSnapshot} kcal</span>}<StatusPill tone={ASSIGNMENT_STATUS_META[item.status].tone}>{ASSIGNMENT_STATUS_META[item.status].label}</StatusPill></div></li>)}</ul></section></div>}
