import { CalendarClock, Plus, UsersRound } from "lucide-react";
import { BookingCard } from "@/components/scheduling/schedule-card";
import { EmptyState } from "@/components/common/empty-state";
import { ErrorState } from "@/components/common/error-state";
import { LoadingRows } from "@/components/common/loading-state";
import { StatusPill } from "@/components/common/status-pill";
import { Button } from "@/components/ui/button";
import { ENROLLMENT_STATUS_META,formatDateISO,formatTime,todayISO } from "@/lib/format";
import type { Booking,ClassEnrollment,GroupClass } from "@/types/models";
export function ClientBookingsSection({bookings,enrollments,classes,loading,error,onAdd}:{bookings:Booking[];enrollments:ClassEnrollment[];classes:GroupClass[];loading:boolean;error:Error|null;onAdd:()=>void}){if(loading)return <LoadingRows rows={4}/>;if(error)return <ErrorState error={error} title="Couldn't load client bookings"/>;const today=todayISO();const upcoming=bookings.filter(b=>b.date>=today&&b.status==="scheduled");const past=bookings.filter(b=>b.date<today||b.status!=="scheduled");const classById=new Map(classes.map(c=>[c.id,c]));return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-section-title">Bookings</h2><p className="text-meta mt-1">Upcoming appointments, PT sessions, and class enrollments.</p></div><Button onClick={onAdd}><Plus/> Create Booking</Button></div>{!bookings.length&&!enrollments.length?<EmptyState icon={CalendarClock} title="No bookings yet" description="Create this client's first booking to add it to the live schedule."/>:<><section><h3 className="mb-3 font-semibold">Upcoming Bookings</h3>{upcoming.length?<div className="grid gap-3">{upcoming.map(b=><BookingCard key={b.id} item={b}/>)}</div>:<p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No upcoming bookings.</p>}</section><section className="surface-card p-5"><h3 className="font-semibold">PT Sessions</h3><p className="text-meta mt-1">{bookings.filter(b=>b.bookingType==="pt").length} session records</p></section><section><h3 className="mb-3 font-semibold">Group Class Enrollments</h3>{enrollments.length?<div className="grid gap-3 sm:grid-cols-2">{enrollments.map(e=>{const c=classById.get(e.groupClassId);return <article key={e.id} className="surface-card p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{c?.name??e.clientNameSnapshot}</p><p className="text-meta">{c?`${formatDateISO(c.date)} · ${formatTime(c.startTime)}`:"Class details unavailable"}</p></div><StatusPill tone={ENROLLMENT_STATUS_META[e.status].tone}>{ENROLLMENT_STATUS_META[e.status].label}</StatusPill></div></article>})}</div>:<p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No group class enrollments.</p>}</section>{past.length?<section><h3 className="mb-3 font-semibold">Past Bookings</h3><div className="grid gap-3">{past.map(b=><BookingCard key={b.id} item={b}/>)}</div></section>:null}</>}</div>}
