import { useEffect, useMemo, useState } from "react";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { FormDialog, Field } from "@/components/common/form-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLive } from "@/hooks/use-live-query";
import { todayISO } from "@/lib/format";
import { bookingSchema, normalizeTrainerId } from "@/lib/scheduling-validation";
import { createBooking, updateBooking } from "@/services/bookings.service";
import { subscribeClients } from "@/services/clients.service";
import { firestoreErrorMessage } from "@/services/firestore.service";
import { subscribeGroupClasses } from "@/services/group-classes.service";
import type { Booking, BookingType, Client, GroupClass } from "@/types/models";

type Errors=Partial<Record<"clientId"|"bookingType"|"trainerNameSnapshot"|"groupClassId"|"date"|"startTime"|"endTime"|"notes",string>>;
export function BookingFormDialog({open,onOpenChange,booking,initialClient}:{open:boolean;onOpenChange:(v:boolean)=>void;booking?:Booking|null;initialClient?:Client|null}){
 const clients=useLive<Client[]>(open?subscribeClients:null,[],[open]);const classes=useLive<GroupClass[]>(open?subscribeGroupClasses:null,[],[open]);
 const [type,setType]=useState<BookingType>("pt");const [clientId,setClientId]=useState("");const [trainer,setTrainer]=useState("");const [classId,setClassId]=useState("");const [date,setDate]=useState(todayISO());const [start,setStart]=useState("09:00");const [end,setEnd]=useState("10:00");const [notes,setNotes]=useState("");const [status,setStatus]=useState<Booking["status"]>("scheduled");const [errors,setErrors]=useState<Errors>({});const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;setType(booking?.bookingType??"pt");setClientId(booking?.clientId??initialClient?.id??"");setTrainer(booking?.trainerNameSnapshot??"");setClassId(booking?.groupClassId??"");setDate(booking?.date??todayISO());setStart(booking?.startTime??"09:00");setEnd(booking?.endTime??"10:00");setNotes(booking?.notes??"");setStatus(booking?.status??"scheduled");setErrors({});},[open,booking,initialClient]);
 const client=clients.data.find(x=>x.id===clientId)??initialClient??null;const group=classes.data.find(x=>x.id===classId)??null;const scheduledClasses=useMemo(()=>classes.data.filter(x=>x.status==="scheduled"),[classes.data]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const trainerName=type==="group_class"?(group?.trainerNameSnapshot??""):trainer;const value={clientId:type==="group_class"?"":clientId,clientNameSnapshot:type==="group_class"?"":client?.fullName??"",bookingType:type,trainerId:normalizeTrainerId(trainerName),trainerNameSnapshot:trainerName,groupClassId:type==="group_class"?classId:"",date:type==="group_class"?(group?.date??date):date,startTime:type==="group_class"?(group?.startTime??start):start,endTime:type==="group_class"?(group?.endTime??end):end,status,notes};const parsed=bookingSchema.safeParse(value);if(!parsed.success){const next:Errors={};for(const issue of parsed.error.issues){const key=issue.path[0] as keyof Errors;if(!next[key])next[key]=issue.message;}setErrors(next);return;}setSaving(true);try{if(booking)await updateBooking(booking.id,parsed.data);else await createBooking(parsed.data);toast.success(booking?"Booking updated":"Booking created");onOpenChange(false);}catch(err){const message=firestoreErrorMessage(err);setErrors({endTime:message});toast.error(message);}finally{setSaving(false)}};
 return <FormDialog open={open} onOpenChange={onOpenChange} title={booking?"Edit booking":"Create booking"} description="Schedule a PT, group class, or general client booking." className="sm:max-w-2xl" footer={<><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" form="booking-form" disabled={saving}>{saving?<Loader2 className="animate-spin"/>:null}{booking?"Save changes":"Create booking"}</Button></>}><form id="booking-form" onSubmit={submit} className="grid gap-4" noValidate>
 <Field label="Booking type" htmlFor="booking-type" error={errors.bookingType} required><Select value={type} onValueChange={v=>setType(v as BookingType)}><SelectTrigger id="booking-type" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pt">PT Session</SelectItem><SelectItem value="group_class">Group Class</SelectItem><SelectItem value="general">General</SelectItem></SelectContent></Select></Field>
 {type==="group_class"?<><Field label="Group class" htmlFor="booking-class" error={errors.groupClassId} required><Select value={classId} onValueChange={setClassId}><SelectTrigger id="booking-class" className="w-full"><SelectValue placeholder="Select a scheduled class"/></SelectTrigger><SelectContent>{scheduledClasses.map(c=><SelectItem key={c.id} value={c.id}>{c.name} · {c.date} · {c.startTime}</SelectItem>)}</SelectContent></Select></Field>{group?<div className="rounded-xl border border-border bg-muted/40 p-4 text-sm"><p className="font-semibold">{group.name}</p><p className="text-meta mt-1">{group.bookedCount} enrolled · {Math.max(0,group.capacity-group.bookedCount)} seats available · Trainer {group.trainerNameSnapshot}</p></div>:null}</>:<Field label="Client" htmlFor="booking-client" error={errors.clientId} required><Select value={clientId} onValueChange={setClientId} disabled={!!initialClient}><SelectTrigger id="booking-client" className="w-full"><SelectValue placeholder="Select a client"/></SelectTrigger><SelectContent>{(initialClient?[initialClient]:clients.data).map(c=><SelectItem key={c.id} value={c.id}>{c.fullName} · {c.clientCode}</SelectItem>)}</SelectContent></Select></Field>}
 {type==="pt"?<Field label="Trainer" htmlFor="booking-trainer" error={errors.trainerNameSnapshot} required><Input id="booking-trainer" maxLength={120} value={trainer} onChange={e=>setTrainer(e.target.value)} placeholder="Trainer name"/></Field>:null}
 {type!=="group_class"?<div className="grid gap-4 sm:grid-cols-3"><Field label="Date" htmlFor="booking-date" error={errors.date} required><Input id="booking-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Start time" htmlFor="booking-start" error={errors.startTime} required><Input id="booking-start" type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="End time" htmlFor="booking-end" error={errors.endTime} required><Input id="booking-end" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div>:null}
 {booking?<Field label="Status" htmlFor="booking-status"><Select value={status} onValueChange={v=>setStatus(v as Booking["status"])}><SelectTrigger id="booking-status" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="scheduled">Scheduled</SelectItem><SelectItem value="completed">Completed</SelectItem><SelectItem value="cancelled">Cancelled</SelectItem><SelectItem value="no_show">No-show</SelectItem></SelectContent></Select></Field>:null}
 <Field label="Notes" htmlFor="booking-notes" error={errors.notes}><Textarea id="booking-notes" rows={3} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></form></FormDialog>;
}
