import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { FormDialog, Field } from "@/components/common/form-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { todayISO } from "@/lib/format";
import { groupClassSchema } from "@/lib/scheduling-validation";
import { firestoreErrorMessage } from "@/services/firestore.service";
import { createGroupClass, updateGroupClass } from "@/services/group-classes.service";
import type { GroupClass, GroupClassStatus } from "@/types/models";
type Errors=Partial<Record<"name"|"description"|"trainerNameSnapshot"|"date"|"startTime"|"endTime"|"capacity"|"location"|"status",string>>;
export function GroupClassFormDialog({open,onOpenChange,item}:{open:boolean;onOpenChange:(v:boolean)=>void;item?:GroupClass|null}){const [name,setName]=useState("");const [description,setDescription]=useState("");const [trainer,setTrainer]=useState("");const [date,setDate]=useState(todayISO());const [start,setStart]=useState("09:00");const [end,setEnd]=useState("10:00");const [capacity,setCapacity]=useState("20");const [location,setLocation]=useState("");const [status,setStatus]=useState<GroupClassStatus>("scheduled");const [errors,setErrors]=useState<Errors>({});const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;setName(item?.name??"");setDescription(item?.description??"");setTrainer(item?.trainerNameSnapshot??"");setDate(item?.date??todayISO());setStart(item?.startTime??"09:00");setEnd(item?.endTime??"10:00");setCapacity(String(item?.capacity??20));setLocation(item?.location??"");setStatus(item?.status??"scheduled");setErrors({});},[open,item]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const parsed=groupClassSchema.safeParse({name,description,trainerNameSnapshot:trainer,date,startTime:start,endTime:end,capacity:capacity.trim()?Number(capacity):0,location,status});if(!parsed.success){const next:Errors={};for(const issue of parsed.error.issues){const key=issue.path[0] as keyof Errors;if(!next[key])next[key]=issue.message;}setErrors(next);return;}setSaving(true);try{if(item)await updateGroupClass(item.id,parsed.data,item.bookedCount);else await createGroupClass(parsed.data);toast.success(item?"Class updated":"Class created");onOpenChange(false);}catch(err){toast.error(firestoreErrorMessage(err));}finally{setSaving(false)}};
 return <FormDialog open={open} onOpenChange={onOpenChange} title={item?"Edit group class":"Create group class"} description="Set the trainer, schedule, location, and member capacity." className="sm:max-w-2xl" footer={<><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" form="class-form" disabled={saving}>{saving?<Loader2 className="animate-spin"/>:null}{item?"Save changes":"Create class"}</Button></>}><form id="class-form" onSubmit={submit} className="grid gap-4" noValidate><Field label="Class name" htmlFor="class-name" error={errors.name} required><Input id="class-name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Description" htmlFor="class-description" error={errors.description}><Textarea id="class-description" maxLength={1000} rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Trainer" htmlFor="class-trainer" error={errors.trainerNameSnapshot} required><Input id="class-trainer" maxLength={120} value={trainer} onChange={e=>setTrainer(e.target.value)}/></Field><Field label="Location" htmlFor="class-location" error={errors.location} required><Input id="class-location" maxLength={160} value={location} onChange={e=>setLocation(e.target.value)}/></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Date" htmlFor="class-date" error={errors.date} required><Input id="class-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Start time" htmlFor="class-start" error={errors.startTime} required><Input id="class-start" type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="End time" htmlFor="class-end" error={errors.endTime} required><Input id="class-end" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Capacity" htmlFor="class-capacity" error={errors.capacity} required><Input id="class-capacity" type="number" min={1} max={500} inputMode="numeric" value={capacity} onChange={e=>setCapacity(e.target.value)}/></Field><Field label="Status" htmlFor="class-status"><Select value={status} onValueChange={v=>setStatus(v as GroupClassStatus)}><SelectTrigger id="class-status" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="scheduled">Scheduled</SelectItem><SelectItem value="completed">Completed</SelectItem><SelectItem value="cancelled">Cancelled</SelectItem></SelectContent></Select></Field></div></form></FormDialog>}
