import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { endOfWeek, format, startOfMonth, startOfWeek, startOfYear } from "date-fns";
import { CalendarDays, MoreHorizontal, Pencil, Plus, ReceiptIndianRupee, Trash2 } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { EmptyState } from "@/components/common/empty-state";
import { ErrorState } from "@/components/common/error-state";
import { LoadingRows } from "@/components/common/loading-state";
import { PageHeader } from "@/components/common/page-header";
import { SearchInput } from "@/components/common/search-input";
import { StatCard } from "@/components/common/stat-card";
import { ExpenseFormDialog } from "@/components/expenses/expense-form-dialog";
import { Button } from "@/components/ui/button";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { useAuth } from "@/hooks/use-auth";
import { useLive } from "@/hooks/use-live-query";
import { formatDate, formatDateISO, formatPrice, todayISO } from "@/lib/format";
import { deleteExpense, subscribeExpenses } from "@/services/expenses.service";
import { firestoreErrorMessage } from "@/services/firestore.service";
import { EXPENSE_CATEGORIES,EXPENSE_PAYMENT_METHODS,type Expense } from "@/types/models";

export const Route=createFileRoute("/_authenticated/expenses")({validateSearch:z.object({create:z.boolean().optional()}),head:()=>({meta:[{title:"Expenses — REBUILD FITNESS"},{name:"description",content:"Track and manage real gym operating expenses."},{property:"og:title",content:"Expenses — REBUILD FITNESS"},{property:"og:description",content:"Track and manage real gym operating expenses."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:ExpensesPage});
function ExpensesPage(){const {create}=Route.useSearch();const {user}=useAuth();const live=useLive<Expense[]>(subscribeExpenses,[],[]);const [search,setSearch]=useState("");const [date,setDate]=useState("");const [category,setCategory]=useState("all");const [payment,setPayment]=useState("all");const [open,setOpen]=useState(Boolean(create));const [editing,setEditing]=useState<Expense|null>(null);const [viewing,setViewing]=useState<Expense|null>(null);const [deleting,setDeleting]=useState<Expense|null>(null);
 const today=todayISO(),now=new Date(),weekStart=format(startOfWeek(now,{weekStartsOn:1}),"yyyy-MM-dd"),weekEnd=format(endOfWeek(now,{weekStartsOn:1}),"yyyy-MM-dd"),monthStart=format(startOfMonth(now),"yyyy-MM-dd"),yearStart=format(startOfYear(now),"yyyy-MM-dd");const sum=(from:string,to=today)=>live.data.filter(e=>e.date>=from&&e.date<=to).reduce((n,e)=>n+e.amount,0);const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return live.data.filter(e=>(!date||e.date===date)&&(category==="all"||e.category===category)&&(payment==="all"||e.paymentMethod===payment)&&(!q||[e.title,e.category,e.notes].some(v=>v.toLowerCase().includes(q))));},[live.data,search,date,category,payment]);
 const remove=async()=>{if(!deleting||!user)return;const item=deleting;setDeleting(null);try{await deleteExpense(item,{uid:user.uid,name:user.displayName||user.email||"Staff"});toast.success("Expense removed",{description:item.title});if(viewing?.id===item.id)setViewing(null);}catch(e){toast.error(firestoreErrorMessage(e));}};
 const cards=[{id:"total",label:"Total Expenses",value:formatPrice(live.data.reduce((n,e)=>n+e.amount,0)),hint:"all recorded expenses",icon:ReceiptIndianRupee,tone:"primary" as const},{id:"month",label:"This Month",value:formatPrice(sum(monthStart)),hint:"current month",icon:CalendarDays,tone:"warning" as const},{id:"today",label:"Today",value:formatPrice(sum(today)),hint:"today",icon:CalendarDays,tone:"info" as const},{id:"week",label:"This Week",value:formatPrice(sum(weekStart,weekEnd)),hint:"Monday to Sunday",icon:CalendarDays,tone:"success" as const},{id:"year",label:"Current Year",value:formatPrice(sum(yearStart)),hint:"year to date",icon:CalendarDays,tone:"violet" as const}];
 return <div className="space-y-6"><PageHeader title="Expenses" description="Track actual operating costs from your Firestore records." breadcrumbs={[{label:"Home",to:"/dashboard"},{label:"Expenses"}]} actions={<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus/> Add Expense</Button>}/>{live.error?<ErrorState error={live.error} title="Couldn't load expenses"/>:null}<div className="no-scrollbar -mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-1 sm:mx-0 sm:grid sm:grid-cols-2 sm:px-0 xl:grid-cols-5">{cards.map(m=><StatCard key={m.id} metric={m} className="w-[74vw] shrink-0 snap-start sm:w-auto"/>)}</div>
 <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SearchInput value={search} onValueChange={setSearch} placeholder="Search title, category or notes…" label="Search expenses"/><Input type="date" aria-label="Filter by date" value={date} onChange={e=>setDate(e.target.value)}/><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Filter by category"><SelectValue placeholder="All categories"/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{EXPENSE_CATEGORIES.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={payment} onValueChange={setPayment}><SelectTrigger aria-label="Filter by payment method"><SelectValue placeholder="All methods"/></SelectTrigger><SelectContent><SelectItem value="all">All methods</SelectItem>{EXPENSE_PAYMENT_METHODS.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
 {live.loading?<LoadingRows rows={5}/>:live.data.length===0?<EmptyState icon={ReceiptIndianRupee} title="No expenses yet" description="Add your first operating expense to begin tracking costs." action={<Button onClick={()=>setOpen(true)}><Plus/> Add expense</Button>}/>:filtered.length===0?<EmptyState icon={ReceiptIndianRupee} title="No matching expenses" description="Try changing your search or filters."/>:<><div className="hidden surface-card overflow-hidden md:block"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Expense</TableHead><TableHead>Category</TableHead><TableHead>Payment Method</TableHead><TableHead className="text-right">Amount</TableHead><TableHead>Created By</TableHead><TableHead className="w-12"><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(e=><TableRow key={e.id}><TableCell>{formatDateISO(e.date)}</TableCell><TableCell className="font-semibold">{e.title}</TableCell><TableCell>{e.category}</TableCell><TableCell>{e.paymentMethod}</TableCell><TableCell className="text-right font-bold tabular-nums">{formatPrice(e.amount)}</TableCell><TableCell>{e.createdBy}</TableCell><TableCell><Actions item={e} view={()=>setViewing(e)} edit={()=>{setEditing(e);setOpen(true)}} remove={()=>setDeleting(e)}/></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 md:hidden">{filtered.map(e=><article key={e.id} className="surface-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{e.title}</p><p className="text-meta mt-1">{formatDateISO(e.date)} · {e.category}</p></div><Actions item={e} view={()=>setViewing(e)} edit={()=>{setEditing(e);setOpen(true)}} remove={()=>setDeleting(e)}/></div><div className="mt-4 flex items-end justify-between gap-3"><div><p className="text-meta">{e.paymentMethod}</p><p className="text-xs text-muted-foreground">{e.createdBy}</p></div><p className="text-xl font-extrabold tabular-nums">{formatPrice(e.amount)}</p></div></article>)}</div></>}</section>
 <ExpenseFormDialog open={open} onOpenChange={setOpen} expense={editing}/><Sheet open={!!viewing} onOpenChange={v=>!v&&setViewing(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-md">{viewing?<><SheetHeader className="text-left"><SheetTitle>{viewing.title}</SheetTitle><SheetDescription>{viewing.category}</SheetDescription></SheetHeader><p className="mt-6 px-4 text-3xl font-extrabold tabular-nums">{formatPrice(viewing.amount)}</p><dl className="mt-5 grid grid-cols-2 gap-3 px-4">{[["Payment method",viewing.paymentMethod],["Expense date",formatDateISO(viewing.date)],["Created by",viewing.createdBy],["Created date",formatDate(viewing.createdAt)]].map(([k,v])=><div key={k} className="rounded-lg border border-border bg-muted/40 p-3"><dt className="text-meta">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl><div className="mt-5 space-y-4 px-4"><div><p className="text-label">Description</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{viewing.description||"No description"}</p></div><div><p className="text-label">Notes</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{viewing.notes||"No notes"}</p></div><Button onClick={()=>{setEditing(viewing);setOpen(true)}}><Pencil/> Edit expense</Button></div></>:null}</SheetContent></Sheet><ConfirmDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)} title="Delete this expense?" description="This permanently removes the expense. The removal remains visible in activity history." confirmLabel="Delete expense" destructive onConfirm={()=>void remove()}/></div>}
function Actions({item,view,edit,remove}:{item:Expense;view:()=>void;edit:()=>void;remove:()=>void}){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Actions for ${item.title}`}><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={view}><ReceiptIndianRupee/> View details</DropdownMenuItem><DropdownMenuItem onSelect={edit}><Pencil/> Edit</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={remove} className="text-destructive focus:text-destructive"><Trash2/> Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
